server:
  port: 8080

spring:
  application:
    name: machopulse-backend
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false


jwt:
  secret: ${JWT_SECRET:ThisIsJustADummyFallbackSecretKeyThatShouldBeLongEnoughForHmacSha256Security123!}
  expiration-ms: ${JWT_EXPIRATION_MS:86400000}